### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by aseques**
Add link about running the scripts

### CODE REVIEW

**Comment by DanSheps** [comment]
I am not sure why this is needed?  Could you elaborate further?

**Comment by aseques** [comment]
It might be only me, but it took about and hour to guess that the scripts needed to be uploaded to netbox and run from there as opposed to running them from my pc.
Maybe if the "running custom scripts" was more in the start of the document or mentioned in the first paragraph I would have understood it faster.
Feel free to discard the update if you think otherwise, thanks

**Comment by DanSheps** [comment]
> Maybe if the "running custom scripts" was more in the start of the document or mentioned in the first paragraph I would have understood it faster.

This might be the better route, and you would need to open that in the netbox repository as a documentation issue first

**Comment by aseques** [comment]
Done, thanks https://github.com/netbox-community/netbox/issues/14082

**Pull request closed without merging**
