### PR TITLE
Orphan primary_ip

### PR DESCRIPTION
**Pull request by renatoalmeidaoliveira**
Flags Devices or VirtualMachines with primary ip addresses that are not assigned to any interface.

### CODE REVIEW

**Comment by abhi1693** [comment]
Which version of NetBox does this happen in? I wasn't aware this was an issue. Was there any bug report raised for this to be fixed?

**Comment by renatoalmeidaoliveira** [comment]
I guess all of them... The steps to reproduce is to assign an IP Address to an Interface and make it primary address of the model. Then change the ip address association to another interface in another modrl

**Comment by renatoalmeidaoliveira** [comment]
I doesn't really recall if I made this report based in a Slack discussion or a issue in Netbox,

**Comment by abhi1693** [comment]
If the issue doesn't exist, it'd be best to raise one after validating this is still reproducible on 3.5.3

**Comment by renatoalmeidaoliveira** [comment]
Just check out, it still "working" in demo.netbox.dev so it should deserves a issue, just have to search if there're any already open

**Comment by renatoalmeidaoliveira** [comment]
@abhi1693 it seens it is related with this issue:
https://github.com/netbox-community/netbox/issues/11934
That should be fixed in 3.5.3,

**Comment by renatoalmeidaoliveira** [comment]
Hey @jsenecal since that problem isn't a problem anymore I think its ok to close it.

**Comment by jsenecal** [comment]
Thanks @renatoalmeidaoliveira

**Pull request closed without merging**
